# Generated by Django 4.2.4 on 2023-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicerecord',
            name='voice',
        ),
        migrations.AddField(
            model_name='voicerecord',
            name='birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voicerecord',
            name='career',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='voicerecord',
            name='certificate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='voicerecord',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voicerecord',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voicerecord',
            name='place',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='voicerecord',
            name='self_intro',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
